### ISSUE TITLE
希望能适配最新版zlm c sdk

### ISSUE THREAD

**Issue by xia-chu** [malegend/ZLMediaKit.Autogen#1]
今天才注意到这个项目，真的很强大，大概查看下接口，发现还是适配的老版本的mk_player接口；
最新版本sdk api有一定新增和改动，主要的改动在mk_player接口，如果作者有空的话，建议重新适配下，我们将把该项目收录到zlm合作项目列表中，让更多用户能使用上这么好的项目，谢谢！

**Comment by malegend** [comment]
好的，感谢夏大关注，尽快做好适配。

**Comment by malegend** [comment]
已做好最新适配, 2022年6月22日拉取自 ZLMediaKit。

**Comment by xia-chu** [comment]
已经收录到zlm项目主页了 感谢！
