### ISSUE TITLE
生成wrapper的CppSharp工程开源吗？

### ISSUE THREAD

**Issue by BackT0TheFuture** [malegend/ZLMediaKit.Autogen#2]
非常强大，但版本又比zlm落下了一些，
请问生成wrapper的CppSharp工程开源吗？
谢谢！

**Comment by malegend** [comment]
CppSharp也是开源的，在GITHUB应该有下载。
因为时间不足，所以只能每隔一段时间更新一次版本。或ZLM有重大阶段性更新后也会随之更新版本。

**Comment by huangyong2016** [comment]
> CppSharp也是开源的，在GITHUB应该有下载。 因为时间不足，所以只能每隔一段时间更新一次版本。或ZLM有重大阶段性更新后也会随之更新版本。

有使用CppSharp生成ZLMediaKit类的处理文章或者工程项目吗？这样可以方便自己处理更新适配
